# Generated by Django 4.0.3 on 2022-03-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_header',
            name='title_2',
            field=models.TextField(max_length=127),
        ),
    ]
