# Generated by Django 4.0.3 on 2022-03-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_header_title_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_post',
            options={'verbose_name': 'blog_Post'},
        ),
        migrations.AddField(
            model_name='blog_post',
            name='author',
            field=models.CharField(default='Admin', max_length=127),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='blog_text1',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='blog_text2',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='blog_text3',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='blog_text4',
            field=models.TextField(default='', max_length=300),
        ),
    ]
