# Generated by Django 4.0.3 on 2022-03-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_post_options_blog_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='title_2',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='blog_text1',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='blog_text2',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='blog_text3',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='blog_text4',
            field=models.TextField(default='', max_length=500),
        ),
    ]
