# Generated by Django 4.0.3 on 2022-03-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_post_title_2_alter_blog_post_blog_text1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='blog_text5',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='', upload_to='comment-author-image/'),
        ),
    ]
