# Generated by Django 4.0.3 on 2022-03-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_post_blog_text5_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='author_position',
            field=models.CharField(default='Admin', max_length=127),
        ),
    ]
