# Generated by Django 4.0.3 on 2022-03-12 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_post_author_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter_body',
            new_name='letter',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commenter_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], default=(('approve', 'Approve'), ('reject', 'Reject')), max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog_post'),
        ),
    ]
