# Generated by Django 4.0.3 on 2022-03-13 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_commenter_body_comment_letter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_post',
            options={'ordering': ['-blog_date'], 'verbose_name': 'blog_Post'},
        ),
    ]
