# Generated by Django 4.0.3 on 2022-03-13 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_commenter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(upload_to='comment-author-image/'),
        ),
        migrations.AlterField(
            model_name='commenter',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_commentters', to='blog.comment'),
        ),
    ]
