# Generated by Django 4.0.3 on 2022-03-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='author_position',
            field=models.CharField(max_length=127),
        ),
    ]
