# Generated by Django 4.0.3 on 2022-03-22 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_comment_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenter',
            name='blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='show_commentters', to='blog.comment'),
        ),
    ]
