# Generated by Django 4.0.3 on 2022-03-22 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_commenter_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commenter',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_commentters', to='blog.comment'),
        ),
    ]
