# Generated by Django 4.0.3 on 2022-03-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_comment_review_count_alter_commenter_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='review_count',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
