# Generated by Django 4.0.3 on 2022-03-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_remove_blog_post_review_count_comment_review_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='review_count',
        ),
    ]
