# Generated by Django 4.0.3 on 2022-03-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_remove_blog_post_review_count_comment_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('reject', 'Reject'), ('approve', 'Approve')], default='reject', max_length=50),
        ),
    ]
