# Generated by Django 4.0.3 on 2022-03-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='author_about',
            field=models.TextField(default='', max_length=500),
        ),
    ]
