# Generated by Django 4.0.3 on 2022-03-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_blog_post_author_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='review_count',
        ),
    ]
