# Generated by Django 4.0.3 on 2022-03-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_name', models.CharField(max_length=127)),
                ('about_title', models.CharField(max_length=127)),
                ('about_who', models.CharField(max_length=100)),
                ('about_text1', models.TextField(max_length=100)),
                ('about_text2', models.TextField(max_length=100)),
                ('about_text3', models.TextField(max_length=100)),
                ('about_text4', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'about_Post',
                'verbose_name_plural': 'about_Posts',
            },
        ),
    ]
