# Generated by Django 4.0.3 on 2022-03-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_post',
            name='about_title',
            field=models.TextField(max_length=127),
        ),
    ]
