# Generated by Django 4.0.3 on 2022-03-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_post_about_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_post',
            name='image',
            field=models.ImageField(default='', upload_to='about_post/'),
        ),
    ]
