# Generated by Django 4.0.3 on 2022-03-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_post',
            name='about_text1',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='about_post',
            name='about_text2',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='about_post',
            name='about_text3',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='about_post',
            name='about_text4',
            field=models.TextField(max_length=300),
        ),
    ]
