# Generated by Django 4.0.3 on 2022-03-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_about_post_about_text1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=50)),
                ('work_subtitle_1', models.CharField(max_length=50)),
                ('work_subtitle_2', models.CharField(max_length=50)),
                ('work_subtitle_3', models.CharField(blank=True, max_length=50, null=True)),
                ('work_subtitle_4', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'about_work',
                'verbose_name_plural': 'about_work',
            },
        ),
    ]
