# Generated by Django 4.0.3 on 2022-03-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_about_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_work',
            options={'verbose_name': 'about_work', 'verbose_name_plural': 'about_works'},
        ),
    ]
