# Generated by Django 4.0.3 on 2022-03-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='index_Post/')),
            ],
            options={
                'verbose_name': 'index_Post',
                'verbose_name_plural': 'index_Posts',
            },
        ),
    ]
