# Generated by Django 4.0.3 on 2022-03-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_post',
            name='post_client',
            field=models.CharField(default='Admin', max_length=20),
        ),
        migrations.AddField(
            model_name='index_post',
            name='post_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='index_post',
            name='post_manager',
            field=models.CharField(default='Admin', max_length=50),
        ),
        migrations.AddField(
            model_name='index_post',
            name='post_name',
            field=models.CharField(default='Project Name', max_length=20),
        ),
        migrations.AddField(
            model_name='index_post',
            name='post_text',
            field=models.TextField(default='Null', max_length=300),
        ),
        migrations.AddField(
            model_name='index_post',
            name='post_title',
            field=models.CharField(default='Null', max_length=127),
        ),
        migrations.AddField(
            model_name='index_post',
            name='post_type',
            field=models.CharField(default='Null', max_length=20),
        ),
    ]
