# Generated by Django 4.0.3 on 2022-03-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_index_post_image1_index_post_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_post',
            name='image3',
            field=models.ImageField(default='', upload_to='index_Post_detail/'),
        ),
    ]
