# Generated by Django 4.0.3 on 2022-03-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_index_post_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_post',
            name='post_date',
            field=models.DateField(auto_now=True),
        ),
    ]
