# Generated by Django 4.0.3 on 2022-03-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_index_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_post',
            name='post_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
